---

- hosts: localhost
  tasks:
    - name: Add local systemd serice config for containers
      tempate:
        src: "{{ item }}.j2"
        dest: "/{{ item }}"
        owner: root
        group: root
        mode: "ug=rw,o=r
      with_items:
        - etc/systemd/system/ansible-container.service
    - name: Enable systemd service and start it
      systemd:
        name: ansible-container
        daemon_reload: yes
        enabled: yes
        state: started