version: 1

defaults:
  init: /usr/local/bin/dumb-init
  web:
    root: /var/www/html
  db:
    database: galano_wp
    root_password: blah123

services:
  db:
    image: mysql:5.5
    command: ["{{ init }}", "docker-entrypoint.sh", "mysqld"]
    volumes:
      - "$PWD/db_data/:/var/lib/mysql/"
      - "$PWD/db_dump/:/docker-entrypoint-initdb.d/:ro"
    environment:
      MYSQL_DATABASE: "{{ db.database }}"
      MYSQL_ROOT_PASSWORD: "{{ db.root_password }}"
  php:
    image: php:5.6-fpm
    working_dir: "{{ web.root }}"
    command: ["{{ init }}", "php-fpm"]
    volumes:
      - "$PWD/html/:{{ web.root }}"
    links:
      - db
  web:
    image: nginx:1.11
    working_dir: "{{ web.root }}"
    command: ["{{ init }}", "nginx", "-g", "daemon off;"]
    ports:
      - "80:80"
    volumes:
      - "$PWD/html/:{{ web.root }}"
    links:
      - php