---

- hosts: all
  gather_facts: no
  tasks:
    - name: Update aptitude cache
      raw: which python || apt-get update
    - name: Install Python
      raw: (which python && which aptitude) || apt-get install -y python python-apt aptitude
    - name: Install dumb-init
      get_url:
        url: https://github.com/Yelp/dumb-init/releases/download/v1.1.3/dumb-init_1.1.3_amd64
        dest: /usr/local/bin/dumb-init
        mode: "ugo+x"
        validate_certs: no

- hosts: web
  vars:
    nginx_dir: /etc/nginx
  tasks:
    - name: Install ca-certificates
      apt: name=ca-certificates state=latest
    - name: Add NGINX config
      template:
        src: "{{ item }}.j2"
        dest: "/{{ item }}"
      with_items:
        - etc/nginx/conf.d/default.conf

- hosts: php
  vars:
    timezone: America/Chicago
  tasks:
    - name: Add configs
      template:
        src: "{{ item }}.j2"
        dest: "/{{ item }}"
      with_items:
        - usr/local/etc/php/php.ini
        - usr/local/etc/php-fpm.d/www.conf

- hosts: db
  tasks:
    - name: Add MySQL overrides config
      template:
        src: "{{ item }}.j2"
        dest: "/{{ item }}"
      with_items:
        - etc/mysql/conf.d/my_custom.cnf