---

- hosts: all
  gather_facts: no
  tasks:
    - name: Update aptitude cache
      raw: which python || apt-get update
    - name: Install Python
      raw: (which python && which aptitude) || apt-get install -y python python-apt aptitude
    - name: Install dumb-init
      get_url:
        url: https://github.com/Yelp/dumb-init/releases/download/v1.1.3/dumb-init_1.1.3_amd64
        dest: /usr/local/bin/dumb-init
        mode: "ugo+x"
        validate_certs: no

- hosts: web
  vars:
    nginx_dir: /etc/nginx
  tasks:
    - name: Install ca-certificates
      apt: name=ca-certificates state=latest
    - name: Add nginx user to www-data group
      user:
        name: nginx
        group: nginx
        groups: www-data
        state: present
    - name: Add NGINX config
      template:
        src: "{{ item }}.j2"
        dest: "/{{ item }}"
        owner: nginx
        group: nginx
        mode: "ug=rw,o=r"
      with_items:
        - etc/nginx/conf.d/default.conf

- hosts: php
  vars:
    timezone: America/Chicago
  tasks:
    - name: Install dependencies required for extensions
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - libfreetype6-dev
        - libjpeg62-turbo-dev
        - libmcrypt-dev
        - libpng12-dev
        - php5-mysql
    - name: Configure build for extensions
      command: docker-php-ext-configure {{ item }}
      with_items:
        - gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ --with-png-dir=/usr/include/
        - pdo_mysql --with-pdo-mysql
    - name: Install extensions
      command: docker-php-ext-install -j1 {{ item }}
      with_items:
        - iconv
        - mcrypt
        - gd
        - mysqli
        - pdo
        - pdo_mysql
    - name: Add configs
      template:
        src: "{{ item }}.j2"
        dest: "/{{ item }}"
        owner: www-data
        group: www-data
        mode: "ug=rw,o=r"
      with_items:
        - usr/local/etc/php/php.ini
        - usr/local/etc/php-fpm.d/www.conf

- hosts: db
  tasks:
    - name: Add MySQL overrides config
      template:
        src: "{{ item }}.j2"
        dest: "/{{ item }}"
        owner: mysql
        group: mysql
        mode: "ug=rw,o=r"
      with_items:
        - etc/mysql/conf.d/my_custom.cnf

- hosts: localhost
  tasks:
    - name: Add local systemd serice config for containers
      tempate:
        src: "{{ item }}.j2"
        dest: "/{{ item }}"
        owner: root
        group: root
        mode: "ug=rw,o=r
      with_items:
        - etc/systemd/system/ansible-container.service
    - name: Enable systemd service and start it
      systemd:
        name: ansible-container
        daemon_reload: yes
        enabled: yes
        state: started